import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ProjectStore,newProject,createClip,clone} from '../../public/studio/packages/core/index.js';
import {Collaboration} from '../../public/studio/packages/collaboration/index.js';
import {MediaLibrary} from '../../public/studio/packages/media/index.js';
function fixture(){const p=newProject();p.media.push({id:'m',name:'Media',type:'video',url:'blob:test',duration:10});p.clips.push(createClip(p.media[0],'v1'));const s=new ProjectStore(p),c=new Collaboration(s);c.id=p.id;c.revision=1;c.base=clone(p);c.dirty=true;return {s,c};}
test('edit during upload retains durable URL in live project',async()=>{const {s,c}=fixture(),file=new Blob(['video'],{type:'video/mp4'});file.name='clip.mp4';c.pendingMedia.set('m',file);const original=globalThis.fetch;let release;globalThis.fetch=()=>new Promise(r=>release=r);try{const pending=c.uploadPending();s.transact('Rename',p=>p.name='New name');release(Response.json({url:'/api/media?id=stored'}));await pending;assert.equal(s.project.media[0].url,'/api/media?id=stored');assert.equal(c.pendingMedia.size,0);}finally{globalThis.fetch=original;c.dispose();}});
test('edits during stale save survive automatic merge',async()=>{const {s,c}=fixture(),remote=clone(s.project);remote.markers.push({id:'marker',time:2,label:'Remote'});let release,count=0;c.request=async()=>{count++;if(count===1){await new Promise(r=>release=r);const e=Error('stale');e.status=409;e.data={project:remote,revision:2};throw e;}return {revision:3};};const saving=c.save();await new Promise(r=>setImmediate(r));s.updateClip(s.project.clips[0].id,{x:321});release();await saving;assert.equal(s.project.clips[0].x,321);assert.equal(s.project.markers.length,1);assert.equal(c.revision,3);assert.equal(s.past.length,0);c.dispose();});
test('remote update invalidates snapshot undo history',async()=>{const {s,c}=fixture();s.updateClip(s.project.clips[0].id,{x:3});c.dirty=false;const remote=clone(s.project);remote.markers.push({id:'m2',time:2});c.request=async()=>({project:remote,revision:2});await c.poll();s.undo();assert.equal(s.project.markers.length,1);assert.equal(s.past.length,0);c.dispose();});
test('cached voice gains mixer connections after audio init',async()=>{let sources=0;const node=()=>({connect(next){return next;},gain:{value:0},pan:{value:0},frequency:{value:0},fftSize:0});const original=globalThis.AudioContext;globalThis.AudioContext=class{constructor(){this.destination=node();}createGain(){return node();}createAnalyser(){return node();}createMediaStreamDestination(){return {...node(),stream:{}};}createMediaElementSource(){sources++;return node();}createStereoPanner(){return node();}createBiquadFilter(){return node();}async resume(){}async close(){}};try{const lib=new MediaLibrary(),el={cloneNode:()=>({volume:.5})},entry={element:el,voices:new Map()};lib.entries.set('m',entry);const voice=lib.voice(entry,'c');assert.equal(voice.source,undefined);await lib.initAudio();assert.ok(voice.source);assert.equal(voice.el.volume,1);assert.equal(sources,1);await lib.initAudio();assert.equal(sources,1);}finally{globalThis.AudioContext=original;}});
