import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {handleStudio} from '../../public/studio/packages/collaboration/server.js';
import {newProject} from '../../public/studio/packages/core/index.js';
const owner={userId:'owner',displayName:'Owner'},editor={userId:'editor',displayName:'Editor'},outsider={userId:'outsider',displayName:'Outsider'};
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));const db={prepare(query){return {args:[],bind(...args){this.args=args;return this;},async first(){return sql.prepare(query).get(...this.args)||null;},async all(){return {results:sql.prepare(query).all(...this.args)};},async run(){return {meta:{changes:Number(sql.prepare(query).run(...this.args).changes)}};}};},async batch(stmts){sql.exec('BEGIN');try{const rows=[];for(const s of stmts)rows.push(await s.run());sql.exec('COMMIT');return rows;}catch(e){sql.exec('ROLLBACK');throw e;}}};const files=new Map(),objects={async put(k,body){files.set(k,new Uint8Array(await new Response(body).arrayBuffer()));},async get(k){const b=files.get(k);return b?{body:b,size:b.byteLength}:null;}};async function call(user,body,query=''){const req=new Request('https://studio.test/api/studio'+query,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const response=await handleStudio(req,{db,objects,user});return {status:response.status,data:await response.json()};}return {call,db,objects,sql};}
test('anonymous access is rejected',async()=>{const f=fixture();assert.equal((await f.call(null)).status,401);});
test('create, list, revise and reload durable project',async()=>{const f=fixture(),created=await f.call(owner,{action:'create',project:newProject('Cut')});assert.equal(created.status,200);const p=created.data.project;p.name='Edited';assert.equal((await f.call(owner,{action:'save',id:p.id,project:p,revision:1})).data.revision,2);assert.equal((await f.call(owner,null,'?id='+p.id)).data.project.name,'Edited');assert.equal((await f.call(owner)).data.projects.length,1);});
test('stale save rejected with latest revision and document',async()=>{const f=fixture(),{data}=await f.call(owner,{action:'create',project:newProject()});await f.call(owner,{action:'save',id:data.project.id,project:data.project,revision:1});const result=await f.call(owner,{action:'save',id:data.project.id,project:data.project,revision:1});assert.equal(result.status,409);assert.equal(result.data.revision,2);});
test('project and media membership cannot be bypassed',async()=>{const f=fixture(),{data}=await f.call(owner,{action:'create',project:newProject()});assert.equal((await f.call(outsider,null,'?id='+data.project.id)).status,404);assert.equal((await f.call(outsider,{action:'save',id:data.project.id,project:data.project,revision:1})).status,404);const upload=new Request('https://studio.test/api/media?project='+data.project.id,{method:'POST',headers:{'Content-Type':'image/png','Content-Length':'3'},body:new Uint8Array([1,2,3])});assert.equal((await handleStudio(upload,{...f,user:outsider})).status,404);});
test('invitation joins, comments persist, revocation blocks access',async()=>{const f=fixture(),{data}=await f.call(owner,{action:'create',project:newProject()});assert.equal((await f.call(editor,{action:'join',code:data.inviteCode})).status,200);assert.equal((await f.call(editor,{action:'comment',id:data.project.id,text:'Trim this',time:2.4})).status,200);assert.equal((await f.call(owner,null,'?id='+data.project.id)).data.comments[0].time,2400);assert.equal((await f.call(editor,{action:'invite',id:data.project.id})).status,403);await f.call(owner,{action:'removeMember',id:data.project.id,userId:editor.userId});assert.equal((await f.call(editor,null,'?id='+data.project.id)).status,404);});
test('reissuing invitation invalidates previous code',async()=>{const f=fixture(),{data}=await f.call(owner,{action:'create',project:newProject()});await f.call(owner,{action:'invite',id:data.project.id});assert.equal((await f.call(editor,{action:'join',code:data.inviteCode})).status,403);});
test('media stored and served only to project members',async()=>{const f=fixture(),{data}=await f.call(owner,{action:'create',project:newProject()});const req=new Request('https://studio.test/api/media?project='+data.project.id+'&name=frame.png',{method:'POST',headers:{'Content-Type':'image/png','Content-Length':'3'},body:new Uint8Array([1,2,3])});const uploaded=await (await handleStudio(req,{...f,user:owner})).json();assert.ok(uploaded.url);const get=await handleStudio(new Request('https://studio.test'+uploaded.url),{...f,user:owner});assert.equal(get.status,200);assert.deepEqual([...new Uint8Array(await get.arrayBuffer())],[1,2,3]);assert.equal((await handleStudio(new Request('https://studio.test'+uploaded.url),{...f,user:outsider})).status,404);});
test('unsafe media URLs and invalid timelines cannot be saved',async()=>{const f=fixture(),p=newProject();p.media.push({id:'x',name:'x',type:'image',url:'https://external.example/x'});assert.equal((await f.call(owner,{action:'create',project:p})).status,400);});
