/** Dependency-free local runner. Node 22.13+. Binds to loopback only. */
import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {readFile,writeFile,mkdir,stat,readdir} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {Readable} from 'node:stream';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {handleStudio} from '../public/studio/packages/collaboration/server.js';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))),data=path.join(root,'.veyra-data');
await mkdir(path.join(data,'media'),{recursive:true});const sql=new DatabaseSync(path.join(data,'studio.sqlite'));sql.exec('PRAGMA journal_mode=WAL;PRAGMA foreign_keys=ON;');
sql.exec('CREATE TABLE IF NOT EXISTS local_migrations(name TEXT PRIMARY KEY)');
for(const filename of (await readdir(path.join(root,'drizzle'))).filter(f=>f.endsWith('.sql')).sort()){if(sql.prepare('SELECT name FROM local_migrations WHERE name=?').get(filename))continue;sql.exec('BEGIN');try{sql.exec(await readFile(path.join(root,'drizzle',filename),'utf8'));sql.prepare('INSERT INTO local_migrations(name) VALUES(?)').run(filename);sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');throw e;}}
function statement(query){return {args:[],bind(...args){this.args=args;return this;},async first(){return sql.prepare(query).get(...this.args)||null;},async all(){return {results:sql.prepare(query).all(...this.args)};},async run(){const result=sql.prepare(query).run(...this.args);return {meta:{changes:Number(result.changes)}};}};}
const db={prepare:statement,async batch(statements){sql.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects={async put(key,body){const file=path.join(data,'media',key);await mkdir(path.dirname(file),{recursive:true});await writeFile(file,Buffer.from(await new Response(body).arrayBuffer()));},async get(key,{range}={}){const file=path.join(data,'media',key);try{const info=await stat(file);let offset=0,length=info.size,hasRange=false;const r=range?.get('range');if(r){const m=/^bytes=(\d*)-(\d*)$/.exec(r);if(m){hasRange=true;if(!m[1]){length=Math.min(info.size,Number(m[2]));offset=info.size-length;}else{offset=Math.min(info.size-1,Number(m[1]));length=(m[2]?Math.min(info.size-1,Number(m[2])):info.size-1)-offset+1;}}}const stream=Readable.toWeb(createReadStream(file,{start:offset,end:offset+length-1}));return {body:stream,size:info.size,range:hasRange?{offset,length}:undefined};}catch{return null;}}};
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.avif':'image/avif','.opus':'audio/ogg','.png':'image/png','.wav':'audio/wav','.json':'application/json','.md':'text/plain'};
const port=Number(process.env.VEYRA_PORT||8080);const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://127.0.0.1:${port}`);if(url.pathname.startsWith('/api/')){if(req.headers.origin&&req.headers.origin!==`http://localhost:${port}`&&req.headers.origin!==`http://127.0.0.1:${port}`){res.writeHead(403);res.end('Origin rejected');return;}const request=new Request(url,{method:req.method,headers:req.headers,body:['GET','HEAD'].includes(req.method)?undefined:Readable.toWeb(req),duplex:'half'});const response=await handleStudio(request,{db,objects,user:{userId:'local-owner',displayName:'Local editor',email:'local@localhost'}});res.writeHead(response.status,Object.fromEntries(response.headers));if(response.body)Readable.fromWeb(response.body).pipe(res);else res.end();return;}let relative=decodeURIComponent(url.pathname);if(relative==='/'||relative==='/studio/')relative='/studio/index.html';const file=path.resolve(root,'public','.'+relative);if(!file.startsWith(path.join(root,'public')+path.sep)){res.writeHead(403);res.end();return;}const bytes=await readFile(file);res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});res.end(bytes);}catch(e){res.writeHead(500,{'Content-Type':'text/plain'});res.end('Request failed: '+e.message);}});server.listen(port,'127.0.0.1',()=>console.log(`Veyra Studio: http://localhost:${port}\nLocal data: .veyra-data/ · Local owner mode`));
